### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './preprocessed_data/VCTK/spker_embed/p317-spker_embed.npy'

### ISSUE THREAD

**Issue by anish-rajan** [keonlee9420/Daft-Exprt#9]
Method to Reproduce Error:
python3 synthesize.py --text "YOUR_DESIRED_TEXT" --restore_step 900000 --mode single --dataset VCTK --ref_audio ../my-voice-analysis/record.wav --speaker_id p317

Error:
FileNotFoundError: [Errno 2] No such file or directory: './preprocessed_data/VCTK/spker_embed/p317-spker_embed.npy'

**Comment by keonlee9420** [comment]
Hi @anish-rajan , you have to preprocess dataset first before training. I recommend you to follow preprocess steps described in README.md.

**Comment by keonlee9420** [comment]
Close due to inactivity.
